edx/edx-reverification-block

edx_reverification_block/xblock/reverification_block.py, edx_reverification_block/xblock/static/html/reverification.html
@wedaly please review this PR. How can I get the "org" from the xmodule_runtime in xBlock?
=> added the re-verification link also the marketing text in studio view

edx_reverification_block/xblock/reverification_block.py, edx_reverification_block/xblock/static/html/reverification.html, edx_reverification_block/xblock/static/html/studio_preview.html
In this PR just added the studio preview
=> ECOM-1206: added the studio preview

edx_reverification_block/xblock/reverification_block.py
=> Aamir khan/ecom 1208 checkpoint configuration

edx_reverification_block/xblock/reverification_block.py, edx_reverification_block/xblock/static/html/checkpoint_edit.html, edx_reverification_block/xblock/static/js/checkpoint_edit.js
ECOM-1437
@awais786 @aamir-khan
=> update reverification xblock model

edx_reverification_block/xblock/reverification_block.py, edx_reverification_block/xblock/static/html/checkpoint_edit.html
=> update sudio view and fields help text

edx_reverification_block/xblock/static/html/checkpoint_edit.html
=> show reverification block field values

edx_reverification_block/xblock/tests/data/basic_scenario.xml, edx_reverification_block/xblock/tests/test_reverification_block.py, requirements/dev.txt
ECOM-1434
@awais786 @aamir-khan
=> add basic tests of edx-reverification-xblock

edx_reverification_block/xblock/reverification_block.py, edx_reverification_block/xblock/static/html/studio_preview.html, edx_reverification_block/xblock/tests/test_reverification_block.py
ECOM-1438
@awais786 @aamir-khan
=> add initial author preview of ICRV

edx_reverification_block/xblock/static/js/checkpoint_edit.js
ECOM-1437
@awais786 @aamir-khan @wedaly 
Added field validations for `related_assessment` and `attempts` fields.
=> add field validations for reverification block

.travis.yml, MANIFEST.in, Makefile, README.rst, edx_reverification_block/xblock/reverification_block.py, edx_reverification_block/xblock/static/html/reverification.html
* Make commands generate minified CSS from sass.
* XBlock includes the CSS in student view fragments.
* Slight refactor of XBlock view code to combine multiple methods
for loading resources.
@zubair-arbi please review.
=> Add CSS generated from sass to student view

edx_reverification_block/xblock/reverification_block.py, edx_reverification_block/xblock/tests/test_reverification_block.py, requirements/dev.txt, requirements/test.txt, settings/dev.py, settings/test.py, stub_verification/admin.py, stub_verification/models.py, stub_verification/service.py, stub_verification/templates/stub_verification/reverify.html, stub_verification/templates/stub_verification/submitted.html, stub_verification/tests/test_service.py, stub_verification/tests/test_views.py, stub_verification/urls.py, stub_verification/views.py, urls.py
* Adds a stub verification service for testing different verification
states in workbench.
* Adds stub verification views to replace the verification flow
(fake photo submission).
* Adds stub verification models to simulate response from the photo
verification service (using Django admin).
=> Stub verification service for testing

edx_reverification_block/xblock/reverification_block.py
=> add end date field for reverification block

edx_reverification_block/xblock/reverification_block.py, edx_reverification_block/xblock/static/html/studio_preview.html, edx_reverification_block/xblock/tests/test_reverification_block.py
ECOM-1438
@awais786 @aamir-khan @wedaly 
Added `validate` method for `Reverification XBlock`.
=> add basic validation for studio preview for reverification block

edx_reverification_block/xblock/reverification_block.py, edx_reverification_block/xblock/static/js/checkpoint_edit.js, edx_reverification_block/xblock/tests/test_reverification_block.py
* Add more error checking in the Studio handler.
* Handle type conversion for attempts field.
* Mark strings in the Studio UI for translation.
* Add test cases for Studio editing.
=> Studio editing: i18n, edge cases, and more tests

edx_reverification_block/xblock/reverification_block.py
@zubair-arbi @awais786 Please review this PR
Added the function to tell the ICRV xblock a credit course requirements
=> ECOM-1592: added the icrv as credit requirement

AUTHORS
=> add authors

edx_reverification_block/xblock/static/html/checkpoint_edit.html, edx_reverification_block/xblock/static/js/checkpoint_edit.js
@zubair-arbi @awais786 @ahsan-ul-haq Please review the changes
=> ECOM-1702: added the dropdown for the attempts

edx_reverification_block/xblock/static/html/reverification.html, edx_reverification_block/xblock/static/sass/_reverification.scss
ECOM-2140
Updated the style of the ICRV intro message.
=> ICRV: Intro Message Styling & Copy

edx_reverification_block/xblock/reverification_block.py, edx_reverification_block/xblock/tests/test_reverification_block.py
@zubair-arbi @aamir-khan @awais786 @tasawernawaz Please review
ECOM-2225
=> Quiz Displaying That Students Not Eligible for Credit

edx_reverification_block/xblock/reverification_block.py, edx_reverification_block/xblock/static/js/checkpoint_edit.js, edx_reverification_block/xblock/tests/test_reverification_block.py, setup.py
_**Note:** Learners/Students will get 5 days extra after the `due date` to submit their verification's for all `ICRV` blocks._
=> Increasing ICRV availability with 5 grace period days.

setup.py
Make setup of ICRV block to include static files e.g, `html`, `js` etc
@awais786 @aamir-khan @ahsan-ul-haq @tasawernawaz
=> include static files in setup

MANIFEST.in, setup.py
@awais786 @aamir-khan @ahsan-ul-haq @tasawernawaz 
Turn setup flag `include_package_data` on for including static files.
=> add static files in ICRV setup

requirements/base.txt, requirements/dev.txt, requirements/test.txt, settings/base.py, setup.py, stub_verification/templates/stub_verification/reverify.html
https://openedx.atlassian.net/browse/TNL-2823
=> Upgrade to Django 1.8

requirements/base.txt, requirements/dev.txt, requirements/test.txt
TNL-3820
@symbolist @macdiesel @doctoryes @nedbat PTAL. Thanks!
=> update satellite repos
